### ISSUE TITLE
metpy's old version problem

### ISSUE THREAD

**Issue by Jhanviuni** [Geet-George/quickdrop#2]
While running the command line: **"from metpy.future import precipitable_water"**
Import error is occurring: 
**ImportError: cannot import name 'precipitable_water' from 'metpy.future'**

As the new version of **metpy** (i.e. 'metpy-1.3.1') no longer has the '**precipitable_water**' in the '**future**' module.

**Comment by Geet-George** [comment]
Thanks for raising this issue, @Jhanviuni. Indeed, the problem seems to be that newer versions of `metpy` have the `precipitable_water` function in the `calc` module, as opposed to `future` in an older version when the script was written. 

Since we would like `quickdrop` to be compatible with the more stable versions of `metpy`, the solution would be:

(a) to change the import statement and
(b) change the package requirements (in `setup.py`) that at least `v1.0` should be used for `metpy`, which seems to be [the version when this change is earliest noted](https://github.com/Unidata/MetPy/commit/a160534f20e2c91f461e2644eb10dbca699abff7). 

I will create a pull request to address this.

**Comment by Geet-George** [comment]
PR #3 should have solved the issue. @Jhanviuni could you check if this particular problem is solved and if so, this issue can be closed.
